Revert "don't recompile exported classes, link to their dll"
The `*_p.h` files do not have any export macros. Instead we now
set -DKNEWSTUFF_STATIC_DEFINE which should prevent the export
macros from expanding to anything even on Windows.

This fixes the compile error for me:

This fixes the compile/link errors of the unit tests:

Linking CXX executable knewstuffentrytest
/home/milian/projects/kf5/src/frameworks/knewstuff/autotests/knewstuffentrytest.cpp:69: error: undefined reference
to 'KNS3::EntryInternal::EntryInternal()'
/home/milian/projects/kf5/src/frameworks/knewstuff/autotests/knewstuffentrytest.cpp:70: error: undefined reference
to 'KNS3::EntryInternal::setEntryXML(QDomElement const&)'
/home/milian/projects/kf5/src/frameworks/knewstuff/autotests/knewstuffentrytest.cpp:71: error: undefined reference
to 'KNS3::EntryInternal::toEntry() const'
/home/milian/projects/kf5/src/frameworks/knewstuff/autotests/knewstuffentrytest.cpp:69: error: undefined reference
to 'KNS3::EntryInternal::~EntryInternal()'
collect2: error: ld returned 1 exit status

and similar. The tests compile again and work properly.

This reverts commit 3ab92282a8909258dc6fa24a3b9d065ee49f8731.

REVIEW: 121093