Fix build error in uploaddialog.ui
Summary:
Building againt current Qt dev fails:

```In file included from /home/nico/kde/src/knewstuff/src/uploaddialog_p.h:22,
 from /home/nico/kde/src/knewstuff/src/uploaddialog.cpp:22:
/home/nico/kde/build/knewstuff/src/ui_uploaddialog.h: In member function ‘void Ui_UploadDialog::setupUi(QWidget*)’:
/home/nico/kde/build/knewstuff/src/ui_uploaddialog.h:173:36: error: no matching function for call to ‘QLineEdit::setEchoMode(bool)’
         password->setEchoMode(false);
                                    ^
```
Using enum instead of bool fixes it

Test Plan: Builds

Reviewers: dhaumann, gregormi, #frameworks, ngraham, apol

Reviewed By: ngraham, apol

Subscribers: apol, kde-frameworks-devel

Tags: #frameworks

Differential Revision: https://phabricator.kde.org/D21108